name: 'Swagger UI Action'
description: 'Generate Swagger UI for API documentation'
author: 'Leon Kiefer'
inputs:
  output:
    description: 'Output path for the generated Swagger UI files'
    required: true
  version:
    description: 'Swagger UI version'
    required: true
    default: '^3.0.0'
  spec-file:
    description: 'A file containing the API definition'
    required: false
  spec-url:
    description: 'An URL pointing to the API definition'
    required: false
  swagger-config-file:
    description: 'A swagger-config file which is copied and added to configUrl'
    required: false
  swagger-config-url:
    description: 'An URL to a swagger-config file which is added to configUrl'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: green
